url: #"https://mysite.github.io" # the base hostname & protocol for your site
title: 'Mobile Legends Addict'


collections:
  heroes:
    permalink: /hero/:path/
    output: true
  guides:
    permalink: /guide/:path/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "README*",
          ".gitignore"] # Don't forget that Jekyll automatically
                          # excludes files with a dot prefix



plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
