url: "https://mladdict.netlify.com/"
title: 'Mobile Legends Addict'


collections:
  heroes:
    permalink: /hero/:path/
    output: true
  guides:
    permalink: /guide/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  -
    scope:
      path: ""
      type: "heroes"
    values:
      layout: "hero"

exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "README*",
          ".gitignore"] # Don't forget that Jekyll automatically
                          # excludes files with a dot prefix



plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
